# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pg_typecast"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bharanee Rathna"]
  s.date = "2012-07-29"
  s.description = "Extensions to pg gem supporting typecasting."
  s.email = ["deepfryed@gmail.com"]
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/extconf.rb",
    "ext/pg_typecast.c",
    "pg_typecast.gemspec",
    "test/helper.rb",
    "test/test_types.rb"
  ]
  s.homepage = "http://github.com/deepfryed/pg_typecast"
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.1")
  s.rubygems_version = "1.8.24"
  s.summary = "Extensions to pg gem supporting typecasting."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pg>, [">= 0.9.0"])
    else
      s.add_dependency(%q<pg>, [">= 0.9.0"])
    end
  else
    s.add_dependency(%q<pg>, [">= 0.9.0"])
  end
end

